package com.liraneto.model.xml.enums.SpellsEnum;

import com.liraneto.model.xml.character.spellSet.SpellPerLevel.actionsList.Action;
import com.liraneto.model.xml.character.spellSet.SpellPerLevel.actionsList.HealDamage;
import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.Arrays;
import java.util.List;

@Getter
@AllArgsConstructor
public enum CantripEnum {
    TRIPLE_TIME(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "Triple Time; SPEED: +10 status", null, null, null, null, "effect")), "60-foot emanation", "0", "&#141; somatic", "1 round", "&lt;p&gt;You dance at a lively tempo, speeding your allies' movement. You and all allies in the area gain a +10-foot status bonus to all Speeds for 1 round.&lt;/p&gt;", "corerulesfocusspellsbard", "&lt;p&gt;&lt;/p&gt;", "2", null, "1", "Triple Time", "1", null, "0", "CANTRIP", "C", "U", null, null, "UNCOMMON BARD CANTRIP COMPOSITION EMOTION ENCHANTMENT MENTAL"),

    TELEKINETIC_PROJECTILE(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( null,Arrays.asList(new HealDamage("0", "d6", "oddcl", "0", "0", "1", "bludgeoning")), null, "1", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null,Arrays.asList(new HealDamage("0", "d6", "oddcl", "0", "0", "1", "piercing")), null, "1", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null,Arrays.asList(new HealDamage("0", "d6", "oddcl", "0", "0", "1", "slashing")), null, "1", null, null, null, null, null, null, null, null, null, null, null, "damage")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;You hurl a loose, unattended object that is within range and that has 1 Bulk or less at the target. Make a spell attack roll against the target. If you hit, you deal bludgeoning, piercing, or slashing damageas appropriate for the object you hurledequal to 1d6 plus your spellcasting ability modifier. No specific traits or magic properties of the hurled item affect the attack or the damage.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(+1) &lt;/b&gt;The damage increases by 1d6.&lt;/p&gt;", "1", null, "1", "Telekinetic Projectile", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, occult", "ATTACK CANTRIP EVOCATION"),

    TANGLEFOOT_4TH(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( "0", null, null, null, "", "0", "1", "1", "minute", null, "SPEED: -10 circumstance; Escape DC", null, null, null, null, "effect"), new Action( "0", null, null, null, "", "0", "1", "1", "minute", null, "(Crit); SPEED: -10 circumstance; Immobilized; Escape DC", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", "1 minute", "&lt;p&gt;A vine covered in sticky sap appears from thin air, flicking from your hand and lashing itself to the target. Attempt a spell attack against the target.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;&lt;/b&gt;&lt;/p&gt;", "4", null, "1", "Tanglefoot (4th)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, primal", "CANTRIP CONJURATION PLANT"),

    TANGLEFOOT_2ND(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( "0", null, null, null, "", "0", "2", "1", null, null, "SPEED: -10 circumstance; Escape DC", null, null, null, null, "effect"), new Action( "0", null, null, null, "", "0", "2", "1", null, null, "(Crit); SPEED: -10 circumstance; Immobilized; Escape DC", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", "2 rounds", "&lt;p&gt;A vine covered in sticky sap appears from thin air, flicking from your hand and lashing itself to the target. Attempt a spell attack against the target.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(4th) &lt;/b&gt;The effects last for 1 minute.&lt;/p&gt;", "2", null, "1", "Tanglefoot (2nd)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, primal", "CANTRIP CONJURATION PLANT"),

    TANGLEFOOT_1ST(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( "0", null, null, null, "", "0", "1", "1", null, null, "SPEED: -10 circumstance; Escape DC", null, null, null, null, "effect"), new Action( "0", null, null, null, "", "0", "1", "1", null, null, "(Crit); SPEED: -10 circumstance; Immobilized; Escape DC", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", "1 round", "&lt;p&gt;A vine covered in sticky sap appears from thin air, flicking from your hand and lashing itself to the target. Attempt a spell attack against the target.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(2nd) &lt;/b&gt;The effects last for 2 rounds.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(4th) &lt;/b&gt;The effects last for 1 minute.&lt;/p&gt;", "1", null, "1", "Tanglefoot (1st)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, primal", "CANTRIP CONJURATION PLANT"),

    STABILIZE(Arrays.asList(new Action( "0", null, null, null, "", "0", "0", "1", null, null, "Stabilize; Unconscious", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;Positive energy shuts death's door. The target loses the dying condition, though it remains unconscious at 0 Hit Points.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;/p&gt;", "1", null, "1", "Stabilize", "1", "30 feet", "0", "CANTRIP", "C", null, "1 dying creature", "divine, primal", "CANTRIP HEALING NECROMANCY POSITIVE"),

    SIGIL_7TH(Arrays.asList(new Action( "0", null, null, null, "", "0", "0", "1", "day", null, "Sigil - Unique Mark on ??", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "unlimited (see below)", "&lt;p&gt;You harmlessly place your unique magical sigil, which is about 1 square inch in size, on the targeted creature or object. The mark can be visible or invisible, and you can change it from one state to another by using an Interact action to touch the target. The mark can be scrubbed or scraped off with 5 minutes of work.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;&lt;/b&gt;&lt;/p&gt;", "7", null, "1", "Sigil (7th)", "1", "touch", "0", "CANTRIP", "C", "H", "1 creature or object", "arcane, divine, occult, primal", "CANTRIP TRANSMUTATION"),

    SIGIL_5TH(Arrays.asList(new Action( "0", null, null, null, "", "0", "0", "1", "day", null, "Sigil - Unique Mark on ?? (1 year on creature)", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "unlimited (see below)", "&lt;p&gt;You harmlessly place your unique magical sigil, which is about 1 square inch in size, on the targeted creature or object. The mark can be visible or invisible, and you can change it from one state to another by using an Interact action to touch the target. The mark can be scrubbed or scraped off with 5 minutes of work. If it's on a creature, it fades naturally over the course of a year. The time before the mark fades increases depending on your heightened level.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The sigil never fades.&lt;/p&gt;", "5", null, "1", "Sigil (5th)", "1", "touch", "0", "CANTRIP", "C", "H", "1 creature or object", "arcane, divine, occult, primal", "CANTRIP TRANSMUTATION"),

    SIGIL_3RD(Arrays.asList(new Action( "0", null, null, null, "", "0", "0", "1", "day", null, "Sigil - Unique Mark on ?? (1 month on creature)", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "unlimited (see below)", "&lt;p&gt;You harmlessly place your unique magical sigil, which is about 1 square inch in size, on the targeted creature or object. The mark can be visible or invisible, and you can change it from one state to another by using an Interact action to touch the target. The mark can be scrubbed or scraped off with 5 minutes of work. If it's on a creature, it fades naturally over the course of a month. The time before the mark fades increases depending on your heightened level.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The sigil instead fades after 1 year.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The sigil never fades.&lt;/p&gt;", "3", null, "1", "Sigil (3rd)", "1", "touch", "0", "CANTRIP", "C", "H", "1 creature or object", "arcane, divine, occult, primal", "CANTRIP TRANSMUTATION"),

    SIGIL_1ST(Arrays.asList(new Action( "0", null, null, null, "", "0", "0", "1", "day", null, "Sigil - Unique Mark on ?? (1 week on creature)", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "unlimited (see below)", "&lt;p&gt;You harmlessly place your unique magical sigil, which is about 1 square inch in size, on the targeted creature or object. The mark can be visible or invisible, and you can change it from one state to another by using an Interact action to touch the target. The mark can be scrubbed or scraped off with 5 minutes of work. If it's on a creature, it fades naturally over the course of a week. The time before the mark fades increases depending on your heightened level.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(3rd) &lt;/b&gt;The sigil instead fades after 1 month.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The sigil instead fades after 1 year.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The sigil never fades.&lt;/p&gt;", "1", null, "1", "Sigil (1st)", "1", "touch", "0", "CANTRIP", "C", "H", "1 creature or object", "arcane, divine, occult, primal", "CANTRIP TRANSMUTATION"),

    SHIELD_9TH(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "AC: +1 circumstance", null, null, null, "self", "effect"), new Action( "0", null, null, null, "", "0", "1", "1", null, null, "RESIST: 25 all", null, null, null, "self", "effect")), null, "0", "&#141; verbal (or &#157;)", "until the start of your next turn", "&lt;p&gt;You raise a magical shield of force. This counts as using the Raise a Shield action, giving you a +1 circumstance bonus to AC until the start of your next turn, but it doesn't require a hand to use.&lt;/p&gt;&lt;p&gt;While the spell is in effect, you can use the Shield Block reaction with your magic shield (see the sidebar). The shield has Hardness 25. After you use Shield Block, the spell ends and you can't cast it again for 10 minutes. Unlike a normal Shield Block, you can use the spell's reaction against the magic missile spell.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Shield Actions&lt;/b&gt;&lt;/p&gt;&lt;p&gt;The shield spell works like a raised shield, and it also gives you the ability to use the Shield Block reaction.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Shield Block &lt;/b&gt;&#157;&lt;/p&gt;&lt;p&gt;You place your shield to ward off a blow. Your shield prevents you from taking an amount of damage up to the shield's Hardness. You and the shield each take any remaining damage, possibly breaking or destroying the shield.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;&lt;/b&gt;&lt;/p&gt;", "9", null, "1", "Shield (9th)", "1", null, "0", "CANTRIP", "C", "H", null, "arcane, divine, occult", "ABJURATION CANTRIP FORCE"),

    SHIELD_7TH(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "AC: +1 circumstance", null, null, null, "self", "effect"), new Action( "0", null, null, null, "", "0", "1", "1", null, null, "RESIST: 20 all", null, null, null, "self", "effect")), null, "0", "&#141; verbal (or &#157;)", "until the start of your next turn", "&lt;p&gt;You raise a magical shield of force. This counts as using the Raise a Shield action, giving you a +1 circumstance bonus to AC until the start of your next turn, but it doesn't require a hand to use.&lt;/p&gt;&lt;p&gt;While the spell is in effect, you can use the Shield Block reaction with your magic shield (see the sidebar). The shield has Hardness 20. After you use Shield Block, the spell ends and you can't cast it again for 10 minutes. Unlike a normal Shield Block, you can use the spell's reaction against the magic missile spell.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Shield Actions&lt;/b&gt;&lt;/p&gt;&lt;p&gt;The shield spell works like a raised shield, and it also gives you the ability to use the Shield Block reaction.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Shield Block &lt;/b&gt;&#157;&lt;/p&gt;&lt;p&gt;You place your shield to ward off a blow. Your shield prevents you from taking an amount of damage up to the shield's Hardness. You and the shield each take any remaining damage, possibly breaking or destroying the shield.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(9th) &lt;/b&gt;The shield has Hardness 25.&lt;/p&gt;", "7", null, "1", "Shield (7th)", "1", null, "0", "CANTRIP", "C", "H", null, "arcane, divine, occult", "ABJURATION CANTRIP FORCE"),

    SHIELD_5TH(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "AC: +1 circumstance", null, null, null, "self", "effect"), new Action( "0", null, null, null, "", "0", "1", "1", null, null, "RESIST: 15 all", null, null, null, "self", "effect")), null, "0", "&#141; verbal (or &#157;)", "until the start of your next turn", "&lt;p&gt;You raise a magical shield of force. This counts as using the Raise a Shield action, giving you a +1 circumstance bonus to AC until the start of your next turn, but it doesn't require a hand to use.&lt;/p&gt;&lt;p&gt;While the spell is in effect, you can use the Shield Block reaction with your magic shield (see the sidebar). The shield has Hardness 15. After you use Shield Block, the spell ends and you can't cast it again for 10 minutes. Unlike a normal Shield Block, you can use the spell's reaction against the magic missile spell.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Shield Actions&lt;/b&gt;&lt;/p&gt;&lt;p&gt;The shield spell works like a raised shield, and it also gives you the ability to use the Shield Block reaction.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Shield Block &lt;/b&gt;&#157;&lt;/p&gt;&lt;p&gt;You place your shield to ward off a blow. Your shield prevents you from taking an amount of damage up to the shield's Hardness. You and the shield each take any remaining damage, possibly breaking or destroying the shield.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The shield has Hardness 20.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(9th) &lt;/b&gt;The shield has Hardness 25.&lt;/p&gt;", "5", null, "1", "Shield (5th)", "1", null, "0", "CANTRIP", "C", "H", null, "arcane, divine, occult", "ABJURATION CANTRIP FORCE"),

    SHIELD_3RD(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "AC: +1 circumstance", null, null, null, "self", "effect"), new Action( "0", null, null, null, "", "0", "1", "1", null, null, "RESIST: 10 all", null, null, null, "self", "effect")), null, "0", "&#141; verbal (or &#157;)", "until the start of your next turn", "&lt;p&gt;You raise a magical shield of force. This counts as using the Raise a Shield action, giving you a +1 circumstance bonus to AC until the start of your next turn, but it doesn't require a hand to use.&lt;/p&gt;&lt;p&gt;While the spell is in effect, you can use the Shield Block reaction with your magic shield (see the sidebar). The shield has Hardness 10. After you use Shield Block, the spell ends and you can't cast it again for 10 minutes. Unlike a normal Shield Block, you can use the spell's reaction against the magic missile spell.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Shield Actions&lt;/b&gt;&lt;/p&gt;&lt;p&gt;The shield spell works like a raised shield, and it also gives you the ability to use the Shield Block reaction.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Shield Block &lt;/b&gt;&#157;&lt;/p&gt;&lt;p&gt;You place your shield to ward off a blow. Your shield prevents you from taking an amount of damage up to the shield's Hardness. You and the shield each take any remaining damage, possibly breaking or destroying the shield.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The shield has Hardness 15.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The shield has Hardness 20.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(9th) &lt;/b&gt;The shield has Hardness 25.&lt;/p&gt;", "3", null, "1", "Shield (3rd)", "1", null, "0", "CANTRIP", "C", "H", null, "arcane, divine, occult", "ABJURATION CANTRIP FORCE"),

    SHIELD_1ST(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "AC: +1 circumstance", null, null, null, "self", "effect"), new Action( "0", null, null, null, "", "0", "1", "1", null, null, "RESIST: 5 all", null, null, null, "self", "effect")), null, "0", "&#141; verbal (or &#157;)", "until the start of your next turn", "&lt;p&gt;You raise a magical shield of force. This counts as using the Raise a Shield action, giving you a +1 circumstance bonus to AC until the start of your next turn, but it doesn't require a hand to use.&lt;/p&gt;&lt;p&gt;While the spell is in effect, you can use the Shield Block reaction with your magic shield (see the sidebar). The shield has Hardness 5. After you use Shield Block, the spell ends and you can't cast it again for 10 minutes. Unlike a normal Shield Block, you can use the spell's reaction against the magic missile spell.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Shield Actions&lt;/b&gt;&lt;/p&gt;&lt;p&gt;The shield spell works like a raised shield, and it also gives you the ability to use the Shield Block reaction.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Shield Block &lt;/b&gt;&#157;&lt;/p&gt;&lt;p&gt;You place your shield to ward off a blow. Your shield prevents you from taking an amount of damage up to the shield's Hardness. You and the shield each take any remaining damage, possibly breaking or destroying the shield.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(3rd) &lt;/b&gt;The shield has Hardness 10.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The shield has Hardness 15.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The shield has Hardness 20.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(9th) &lt;/b&gt;The shield has Hardness 25.&lt;/p&gt;", "1", null, "1", "Shield (1st)", "1", null, "0", "CANTRIP", "C", "H", null, "arcane, divine, occult", "ABJURATION CANTRIP FORCE"),

    READ_AURA_6TH(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "Study objects, learn if they're magical and the school.", null, null, null, null, "effect")), null, "0", "1 minute (somatic, verbal)", null, "&lt;p&gt;You focus on the target object, opening your mind to perceive magical auras. When the casting is complete, you know whether that item is magical, and if it is, you learn the school of magic (pages 297-298).&lt;/p&gt;&lt;p&gt;If the object is illusory, you detect this only if the effect's level is lower than the level of your read aura spell.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;&lt;/b&gt;&lt;/p&gt;", "6", null, "1", "Read Aura (6th)", "1", "30 feet", "0", "CANTRIP", "C", "H", "Any number of objects", "arcane, divine, occult, primal", "CANTRIP DETECTION DIVINATION"),

    READ_AURA_3RD(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "Study objects, learn if they're magical and the school.", null, null, null, null, "effect")), null, "0", "1 minute (somatic, verbal)", null, "&lt;p&gt;You focus on the target object, opening your mind to perceive magical auras. When the casting is complete, you know whether that item is magical, and if it is, you learn the school of magic (pages 297-298).&lt;/p&gt;&lt;p&gt;If the object is illusory, you detect this only if the effect's level is lower than the level of your read aura spell.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(6th) &lt;/b&gt;You can target any number of objects.&lt;/p&gt;", "3", null, "1", "Read Aura (3rd)", "1", "30 feet", "0", "CANTRIP", "C", "H", "10 objects", "arcane, divine, occult, primal", "CANTRIP DETECTION DIVINATION"),

    READ_AURA_1ST(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "Study an object, learn if it's magical and it's school.", null, null, null, null, "effect")), null, "0", "1 minute (somatic, verbal)", null, "&lt;p&gt;You focus on the target object, opening your mind to perceive magical auras. When the casting is complete, you know whether that item is magical, and if it is, you learn the school of magic (pages 297-298).&lt;/p&gt;&lt;p&gt;If the object is illusory, you detect this only if the effect's level is lower than the level of your read aura spell.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(3rd) &lt;/b&gt;You can target up to 10 objects.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(6th) &lt;/b&gt;You can target any number of objects.&lt;/p&gt;", "1", null, "1", "Read Aura (1st)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 object", "arcane, divine, occult, primal", "CANTRIP DETECTION DIVINATION"),

    RAY_OF_FROST(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d4", "oddcl", "0", "0", "1", "cold")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( "0", null, null, null, "", "0", "1", "1", null, null, "(Crit); SPEED: -10 status", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;You blast an icy ray. Make a spell attack roll. The ray deals cold damage equal to 1d4 + your spellcasting ability modifier.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(+1) &lt;/b&gt;The damage increases by 1d4.&lt;/p&gt;", "1", null, "1", "Ray of Frost", "1", "120 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, primal", "ATTACK CANTRIP COLD EVOCATION"),

    PRODUCE_FLAME(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d4", "oddcl", "0", "0", "1", "fire")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, Arrays.asList(new HealDamage("0", "d4", "oddcl", "0", "0", "1", "fire, persistent")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;A small ball of flame appears in the palm of your hand, and you lash out with it either in melee or at range. Make a spell attack roll against your target's AC. This is normally a ranged attack, but you can also make a melee attack against a creature in your unarmed reach. On a success, you deal 1d4 fire damage plus your spellcasting ability modifier. On a critical success, the target takes double damage and 1d4 persistent firedamage.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(+1) &lt;/b&gt;Increase the damage by 1d4 and the persistent damage on a critical hit by 1d4.&lt;/p&gt;", "1", null, "1", "Produce Flame", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, primal", "ATTACK CANTRIP EVOCATION FIRE"),

    MESSAGE_3RD(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "Message a creature within 500'", null, null, null, null, "effect")), null, "0", "&#141; verbal", "see below", "&lt;p&gt;You mouth words quietly, but instead of coming out of your mouth, they're transferred directly to the ears of the target. While others can't hear your words any better than if you normally mouthed them, the target can hear your words as if they were standing next to you. The target can give a brief response as a reaction, or as a free action on their next turn if they wish, but they must be able to see you and be within range to do so. If they respond, their response is delivered directly to your ear, just like the original message.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;&lt;/b&gt;&lt;/p&gt;", "3", null, "1", "Message (3rd)", "1", "500 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, divine, occult", "AUDITORY CANTRIP ILLUSION LINGUISTIC MENTAL"),

    PRESTIDIGITATION(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "(Sustained) Prestidigitation", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "sustained", "&lt;p&gt;The simplest magic does your bidding. You can perform simple magical effects for as long as you Sustain the Spell. Each time you Sustain the Spell, you can choose one of four options.&lt;/p&gt;&lt;h&gt;Cook&lt;/h&gt;&lt;p&gt;Cool, warm, or flavor 1 pound of nonliving material.&lt;/p&gt;&lt;h&gt;Lift&lt;/h&gt;&lt;p&gt;Slowly lift an unattended object of light Bulk or less 1 foot off the ground.&lt;/p&gt;&lt;h&gt;Make&lt;/h&gt;&lt;p&gt;Create a temporary object of negligible Bulk, made of congealed magical substance. The object looks crude and artificial and is extremely fragileit can't be used as a tool, weapon, or spell component.&lt;/p&gt;&lt;h&gt;Tidy&lt;/h&gt;&lt;p&gt;Color, clean, or soil an object of light Bulk or less. You can affect an object of 1 Bulk with 10 rounds of concentration, and a larger object a 1 minute per Bulk.&lt;/p&gt;&lt;p&gt;Prestidigitation can't deal damage or cause adverse conditions. Any actual change to an object (beyond what is noted above) persists only as long as you Sustain the Spell.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;/p&gt;", "1", null, "1", "Prestidigitation", "1", "10 feet", "0", "CANTRIP", "C", null, "1 object (cook, lift, or tidyonly)", "arcane, divine, occult, primal", "CANTRIP EVOCATION"),

    MESSAGE_1ST(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "Message a creature within 120'", null, null, null, null, "effect")), null, "0", "&#141; verbal", "see below", "&lt;p&gt;You mouth words quietly, but instead of coming out of your mouth, they're transferred directly to the ears of the target. While others can't hear your words any better than if you normally mouthed them, the target can hear your words as if they were standing next to you. The target can give a brief response as a reaction, or as a free action on their next turn if they wish, but they must be able to see you and be within range to do so. If they respond, their response is delivered directly to your ear, just like the original message.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(3rd) &lt;/b&gt;The spell's range increases to 500 feet.&lt;/p&gt;", "1", null, "1", "Message (1st)", "1", "120 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, divine, occult", "AUDITORY CANTRIP ILLUSION LINGUISTIC MENTAL"),

    MAGE_HAND_7TH(Arrays.asList(new Action( "0", null, null, null, "", "0", "0", "1", null, null, "(Sustained) Mage Hand", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "sustained", "&lt;p&gt;You create a single magical hand, either invisible or ghostlike, that grasps the target object and moves it slowly up to 20 feet. Because you're levitating the object, you can move it in any direction. When you Sustain the Spell, you can move the object an additional 20 feet. If the object is in the air when the spell ends, the object falls.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;&lt;/b&gt;&lt;/p&gt;", "7", null, "1", "Mage Hand (7th)", "1", "60 feet", "0", "CANTRIP", "C", "H", "1 unattended object of 2 Bulk or less", "arcane, occult", "CANTRIP EVOCATION"),

    MAGE_HAND_5TH(Arrays.asList(new Action( "0", null, null, null, "", "0", "0", "1", null, null, "(Sustained) Mage Hand", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "sustained", "&lt;p&gt;You create a single magical hand, either invisible or ghostlike, that grasps the target object and moves it slowly up to 20 feet. Because you're levitating the object, you can move it in any direction. When you Sustain the Spell, you can move the object an additional 20 feet. If the object is in the air when the spell ends, the object falls.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The range increases to 60 feet, and you can target an unattended object with a Bulk of 2 or less.&lt;/p&gt;", "5", null, "1", "Mage Hand (5th)", "1", "60 feet", "0", "CANTRIP", "C", "H", "1 unattended object of 1 Bulk or less", "arcane, occult", "CANTRIP EVOCATION"),

    MAGE_HAND_3RD(Arrays.asList(new Action( "0", null, null, null, "", "0", "0", "1", null, null, "(Sustained) Mage Hand", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "sustained", "&lt;p&gt;You create a single magical hand, either invisible or ghostlike, that grasps the target object and moves it slowly up to 20 feet. Because you're levitating the object, you can move it in any direction. When you Sustain the Spell, you can move the object an additional 20 feet. If the object is in the air when the spell ends, the object falls.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The range increases to 60 feet, and you can target an unattended object with a Bulk of 1 or less.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The range increases to 60 feet, and you can target an unattended object with a Bulk of 2 or less.&lt;/p&gt;", "3", null, "1", "Mage Hand (3rd)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 unattended object of 1 Bulk or less", "arcane, occult", "CANTRIP EVOCATION"),

    MAGE_HAND_1ST(Arrays.asList(new Action( "0", null, null, null, "", "0", "0", "1", null, null, "(Sustained) Mage Hand", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "sustained", "&lt;p&gt;You create a single magical hand, either invisible or ghostlike, that grasps the target object and moves it slowly up to 20 feet. Because you're levitating the object, you can move it in any direction. When you Sustain the Spell, you can move the object an additional 20 feet. If the object is in the air when the spell ends, the object falls.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(3rd) &lt;/b&gt;You can target an unattended object with a Bulk of 1 or less.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The range increases to 60 feet, and you can target an unattended object with a Bulk of 1 or less.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The range increases to 60 feet, and you can target an unattended object with a Bulk of 2 or less.&lt;/p&gt;", "1", null, "1", "Mage Hand (1st)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 unattended object of light Bulk or less", "arcane, occult", "CANTRIP EVOCATION"),

    LIGHT_4TH(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", "day", null, "Light Spell - 60' radius (dim next 60')", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "until the next time you make your daily preparations", "&lt;p&gt;The object glows, casting bright light in a 60-foot radius (and dim light for the next 60 feet). If you cast this spell again on a second object, the light spell on the first object ends.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;&lt;/b&gt;&lt;/p&gt;", "4", null, "1", "Light (4th)", "1", "touch", "0", "CANTRIP", "C", "H", "1 object of 1 Bulk or less, either unattended or possessed by you or a willing ally", "arcane, divine, occult, primal", "CANTRIP EVOCATION LIGHT"),

    LIGHT_1ST(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", "day", null, "Light Spell - 20' radius (dim next 20')", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "until the next time you make your daily preparations", "&lt;p&gt;The object glows, casting bright light in a 20-foot radius (and dim light for the next 20 feet) like a torch. If you cast this spell again on a second object, the light spell on the first object ends.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(4th) &lt;/b&gt;The object sheds bright light in a 60-foot radius (and dim light for the next 60 feet).&lt;/p&gt;", "1", null, "1", "Light (1st)", "1", "touch", "0", "CANTRIP", "C", "H", "1 object of 1 Bulk or less, either unattended or possessed by you or a willing ally", "arcane, divine, occult, primal", "CANTRIP EVOCATION LIGHT"),

    KNOW_DIRECTION_7TH(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "You know where north is or the direction to a familiar location.", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;In your mind's eye, you see a path northward. You immediately know which direction is north (if it exists at your current location) or you can instead know the direction to a familiar location, such as a previous home or a favorite tavern.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;&lt;/b&gt;&lt;/p&gt;", "7", null, "1", "Know Direction (7th)", "1", null, "0", "CANTRIP", "C", "H", null, "divine, occult, primal", "CANTRIP DETECTION DIVINATION"),

    KNOW_DIRECTION_1ST(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "You know where north is.", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;In your mind's eye, you see a path northward. You immediately know which direction is north (if it exists at your current location).&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;You can instead know the direction to a familiar location, such as a previous home or a favorite tavern.&lt;/p&gt;", "1", null, "1", "Know Direction (1st)", "1", null, "0", "CANTRIP", "C", "H", null, "divine, occult, primal", "CANTRIP DETECTION DIVINATION"),

    INSPIRE_DEFENSE(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "Inspire Defense; AC: 1 status; SAVE: 1 status; RESIST: [HCL] physical", null, null, null, null, "effect")), "60-foot emanation", "0", "&#141; verbal", "1 round", "&lt;p&gt;You inspire your allies to protect themselves more effectively. You and all allies in the area gain a +1 status bonus to AC and saving throws, as well as resistance equal to half the spell's level to physical damage.&lt;/p&gt;", "corerulesfocusspellsbard", "&lt;p&gt;&lt;/p&gt;", "2", null, "1", "Inspire Defense", "1", null, "0", "CANTRIP", "C", "U", null, null, "UNCOMMON BARD CANTRIP COMPOSITION EMOTION ENCHANTMENT MENTAL"),

    INSPIRE_COURAGE(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "Inspire Courage; ATK: 1 status; DMG: 1 status; DMGS: 1 status; SAVE: 1 fear, status", null, null, null, null, "effect")), "60-foot emanation", "0", "&#141; verbal", "1 round", "&lt;p&gt;You inspire your allies with words or tunes of encouragement. You and all allies in the area gain a +1 status bonus to attack rolls, damage rolls, and saves against fear effects.&lt;/p&gt;", "corerulesfocusspellsbard", "&lt;p&gt;&lt;/p&gt;", "1", null, "1", "Inspire Courage", "1", null, "0", "CANTRIP", "C", "U", null, null, "UNCOMMON BARD CANTRIP COMPOSITION EMOTION ENCHANTMENT MENTAL"),

    INSPIRE_COMPETENCE(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "Inspire Competence", null, null, null, "self", "effect")), null, "0", "&#141; verbal", "1 round", "&lt;p&gt;Your encouragement inspires your ally to succeed at a task. This counts as having taken sufficient preparatory actions to Aid your ally on a skill check of your choice, regardless of the circumstances. When you later use the Aid reaction, you can roll Performance instead of the normal skill check, and if you roll a failure, you get a success instead. If you are legendary in Performance, you automatically critically succeed.&lt;/p&gt;&lt;p&gt;The GM might rule that you can't use this ability if the act of encouraging your ally would interfere with the skill check (such as a check to Sneak quietly or maintain a disguise).&lt;/p&gt;", "corerulesfocusspellsbard", "&lt;p&gt;&lt;/p&gt;", "1", null, "1", "Inspire Competence", "1", "60 feet", "0", "CANTRIP", "C", "U", "1 ally", null, "UNCOMMON BARD CANTRIP COMPOSITION EMOTION ENCHANTMENT MENTAL"),

    HOUSE_OF_IMAGINARY_WALLS(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "House of Imaginary Walls; AC 10; Hardness 10; HPs 20", null, null, null, "self", "effect"), new Action( "0", null, null, null, "", "0", "1", "1", "minute", null, "House of Imaginary Walls - Immune", null, null, null, null, "effect")), null, "0", "&#141; somatic", "1 round", "&lt;p&gt;You mime creating an invisible 10-foot-by-10-foot stretch of wall adjacent to you and within your reach. The wall is solid to those creatures that don't disbelieve it, even incorporeal creatures. You and your allies can voluntarily believe the wall exists to continue to treat it as solid, for instance to climb onto it. A creature that disbelieves the illusion is temporarily immune to your house of imaginary walls for 1 minute. The wall doesn't block creatures that didn't see your visual performance, nor does it block objects. The wall has AC 10, Hardness equal to double the spell's level, and HP equal to quadruple the spell's level.&lt;/p&gt;", "corerulesfocusspellsbard", "&lt;p&gt;&lt;/p&gt;", "5", null, "1", "House of Imaginary Walls", "1", "touch", "0", "CANTRIP", "C", "U", null, null, "UNCOMMON BARD CANTRIP COMPOSITION ILLUSION VISUAL"),

    GUIDANCE(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "ATK: 1 status; SKILL: 1 status; SAVE: 1 status", null, null, null, null, "effect"), new Action( "0", null, null, null, "", "0", "1", "1", "hour", null, "Guidance - Immune", null, null, null, null, "effect")), null, "0", "&#141; verbal", "until the start of your next turn", "&lt;p&gt;You ask for divine guidance, granting the target a +1 status bonus to one attack roll, Perception check, saving throw, or skill check the target attempts before the duration ends. The target chooses which roll to use the bonus on before rolling. If the target uses the bonus, the spell ends. Either way, the target is then temporarily immune for 1 hour.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;/p&gt;", "1", null, "1", "Guidance", "1", "30 feet", "0", "CANTRIP", "C", null, "1 creature", "divine, occult, primal", "CANTRIP DIVINATION"),

    GHOST_SOUND_5TH(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "(Sustained) Ghost Sound", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "sustained", "&lt;p&gt;You create an auditory illusion of simple sounds that has a maximum volume equal to four normal humans shouting. The sounds emanate from a square you designate within range. You can't create intelligible words or other intricate sounds (such as music).&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;&lt;/b&gt;&lt;/p&gt;", "5", null, "1", "Ghost Sound (5th)", "1", "120 feet", "0", "CANTRIP", "C", "H", null, "arcane, occult", "AUDITORY CANTRIP ILLUSION"),

    GHOST_SOUND_3RD(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "(Sustained) Ghost Sound", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "sustained", "&lt;p&gt;You create an auditory illusion of simple sounds that has a maximum volume equal to four normal humans shouting. The sounds emanate from a square you designate within range. You can't create intelligible words or other intricate sounds (such as music).&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The range increases to 120 feet.&lt;/p&gt;", "3", null, "1", "Ghost Sound (3rd)", "1", "60 feet", "0", "CANTRIP", "C", "H", null, "arcane, occult", "AUDITORY CANTRIP ILLUSION"),

    GHOST_SOUND_1ST(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "(Sustained) Ghost Sound", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "sustained", "&lt;p&gt;You create an auditory illusion of simple sounds that has a maximum volume equal to four normal humans shouting. The sounds emanate from a square you designate within range. You can't create intelligible words or other intricate sounds (such as music).&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(3rd) &lt;/b&gt;The range increases to 60 feet.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The range increases to 120 feet.&lt;/p&gt;", "1", null, "1", "Ghost Sound (1st)", "1", "30 feet", "0", "CANTRIP", "C", "H", null, "arcane, occult", "AUDITORY CANTRIP ILLUSION"),

    FORBIDDING_WARD_6TH(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", "minute", null, "(Sustained) Forbidding Ward", null, null, null, "self", "effect"), new Action( "0", null, null, null, "", "0", "1", "1", "minute", null, "AC: 2 status; SAVE: 2 status; vs 1 enemy", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", "sustained up to 1 minute", "&lt;p&gt;You ward an ally against the attacks and hostile spells from the target enemy. The target ally gains a +2 status bonus to Armor Class and saving throws against the target enemy's attacks, spells, and other effects.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;&lt;/b&gt;&lt;/p&gt;", "6", null, "1", "Forbidding Ward (6th)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 ally and 1 enemy", "divine, occult", "ABJURATION CANTRIP"),

    FORBIDDING_WARD_1ST(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", "minute", null, "(Sustained) Forbidding Ward", null, null, null, "self", "effect"), new Action( "0", null, null, null, "", "0", "1", "1", "minute", null, "AC: 1 status; SAVE: 1 status; vs 1 enemy", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", "sustained up to 1 minute", "&lt;p&gt;You ward an ally against the attacks and hostile spells from the target enemy. The target ally gains a +1 status bonus to Armor Class and saving throws against the target enemy's attacks, spells, and other effects.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(6th) &lt;/b&gt;The status bonus increases to +2.&lt;/p&gt;", "1", null, "1", "Forbidding Ward (1st)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 ally and 1 enemy", "divine, occult", "ABJURATION CANTRIP"),

    ELECTRIC_ARC(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, "half", "0", "reflex", null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d4", "oddcl", "0", "0", "1", "electricity")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;An arc of lightning leaps from one target to another. You deal electricity damage equal to 1d4 plus your spellcasting abilitymodifier.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(+1) &lt;/b&gt;The damage increases by 1d4.&lt;/p&gt;", "1", null, "1", "Electric Arc", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 or 2 creatures", "arcane, primal", "CANTRIP ELECTRICITY EVOCATION"),

    DIVINE_LANCE(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d4", "oddcl", "0", "0", "1", "chaotic")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, Arrays.asList(new HealDamage("0", "d4", "oddcl", "0", "0", "1", "evil")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, Arrays.asList(new HealDamage("0", "d4", "oddcl", "0", "0", "1", "good")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, Arrays.asList(new HealDamage("0", "d4", "oddcl", "0", "0", "1", "lawful")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;You unleash a beam of divine energy. Choose an alignment your deity has (chaotic, evil, good, or lawful). You can't cast this spell if you don't have a deity or if your deity is true neutral. Make a ranged spell attack roll against the target's AC. On a hit, the target takes damage of the chosen alignment type equal to 1d4 + your spellcasting ability modifier (double damage on a critical hit). The spell gains the trait of the alignment you chose.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(+1) &lt;/b&gt;The damage increases by 1d4.&lt;/p&gt;", "1", null, "1", "Divine Lance", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 creature", "divine", "ATTACK CANTRIP EVOCATION"),

    DISRUPT_UNDEAD(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, "half", "0", "fortitude", null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d6", "oddcl", "0", "0", "1", "positive")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( "0", null, null, null, "", "0", "1", "1", null, null, "(Crit); Enfeebled: 1", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;You lance the target with energy. You deal 1d6 positive damage plus your spellcasting ability modifier. The target must attempt a basic Fortitude save. If the creature critically fails the save, it is also enfeebled 1 for 1 round.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(+1) &lt;/b&gt;The damage increases by 1d6.&lt;/p&gt;", "1", null, "1", "Disrupt Undead", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 undead creature", "divine, primal", "CANTRIP NECROMANCY POSITIVE"),

    DIRGE_OF_DOOM(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "Frightened: 1", null, null, null, null, "effect")), "30-foot emanation", "0", "&#141; verbal", "1 round", "&lt;p&gt;Foes within the area are frightened 1. They can't reduce their frightened value below 1 while they remain in the area.&lt;/p&gt;", "corerulesfocusspellsbard", "&lt;p&gt;&lt;/p&gt;", "3", null, "1", "Dirge of Doom", "1", null, "0", "CANTRIP", "C", "U", null, null, "UNCOMMON BARD CANTRIP COMPOSITION EMOTION ENCHANTMENT Fear Mental"),

    DETECT_MAGIC_4TH(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "Detect the presense of magic and school of strongest effect within 30'. You can roughly pinpoint this source.", null, null, null, null, "effect")), "30-foot emanation", "0", "&#143; somatic, verbal", null, "&lt;p&gt;You send out a pulse that registers the presence of magic. You learn the school of magic for the highest-level effect within range that the spell detects. If multiple effects are equally strong, the GM determines which you learn. You also pinpoint the source of the highest-level magic. Like for an imprecise sense, you don't learn the exact location, but can narrow down the source to within a 5-foot cube (or the nearest if larger than that).&lt;/p&gt;&lt;p&gt;You can choose to ignore magic you're fully aware of, such as the magic items and ongoing spells of you and your allies.&lt;/p&gt;&lt;p&gt;You detect illusion magic only if that magic's effect has a lower level than the level of your detect magic spell. However, items that have an illusion aura but aren't deceptive in appearance (such as an invisibility potion) typically are detected normally.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;&lt;/b&gt;&lt;/p&gt;", "4", null, "1", "Detect Magic (4th)", "1", null, "0", "CANTRIP", "C", "H", null, "arcane, divine, occult, primal", "CANTRIP DETECTION DIVINATION"),

    DETECT_MAGIC_3RD(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "Detect the presense of magic and school of strongest effect within 30'", null, null, null, null, "effect")), "30-foot emanation", "0", "&#143; somatic, verbal", null, "&lt;p&gt;You send out a pulse that registers the presence of magic. You learn the school of magic for the highest-level effect within range that the spell detects. If multiple effects are equally strong, the GM determines which you learn. You can choose to ignore magic you're fully aware of, such as the magic items and ongoing spells of you and your allies.&lt;/p&gt;&lt;p&gt;You detect illusion magic only if that magic's effect has a lower level than the level of your detect magic spell. However, items that have an illusion aura but aren't deceptive in appearance (such as an invisibility potion) typically are detected normally.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(4th) &lt;/b&gt;As 3rd level, but you also pinpoint the source of the highest-level magic. Like for an imprecise sense, you don't learn the exact location, but can narrow down the source to within a 5-foot cube (or the nearest if larger than that).&lt;/p&gt;", "3", null, "1", "Detect Magic (3rd)", "1", null, "0", "CANTRIP", "C", "H", null, "arcane, divine, occult, primal", "CANTRIP DETECTION DIVINATION"),

    DETECT_MAGIC_1ST(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "Detect the presense of magic within 30'", null, null, null, null, "effect")), "30-foot emanation", "0", "&#143; somatic, verbal", null, "&lt;p&gt;You send out a pulse that registers the presence of magic. You receive no information beyond the presence or absence of magic. You can choose to ignore magic you're fully aware of, such as the magic items and ongoing spells of you and your allies.&lt;/p&gt;&lt;p&gt;You detect illusion magic only if that magic's effect has a lower level than the level of your detect magic spell. However, items that have an illusion aura but aren't deceptive in appearance (such as an invisibility potion) typically are detected normally.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(3rd) &lt;/b&gt;You learn the school of magic for the highest-level effect within range that the spell detects. If multiple effects are equally strong, the GM determines which you learn.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(4th) &lt;/b&gt;As 3rd level, but you also pinpoint the source of the highest-level magic. Like for an imprecise sense, you don't learn the exact location, but can narrow down the source to within a 5-foot cube (or the nearest if larger than that).&lt;/p&gt;", "1", null, "1", "Detect Magic (1st)", "1", null, "0", "CANTRIP", "C", "H", null, "arcane, divine, occult, primal", "CANTRIP DETECTION DIVINATION"),

    DAZE_9TH(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, null, "will", null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d6,d6,d6,d6", null, "0", "0", "1", "mental")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( "0", null, null, null, "", "0", "0", "1", null, null, "(Crit); Stunned: 1", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", "1 round", "&lt;p&gt;You cloud the target's mind and daze it with a mental jolt. The jolt deals mental damage equal to your spellcasting ability modifier; the target must attempt a basic Will save. If the target critically fails the save, it is also stunned 1.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(+2) &lt;/b&gt;The damage increases by 1d6.&lt;/p&gt;", "9", null, "1", "Daze (9th)", "1", "60 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, divine, occult", "CANTRIP ENCHANTMENT MENTAL NONLETHAL"),

    DAZE_7TH(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, null, "will", null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d6,d6,d6", null, "0", "0", "1", "mental")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( "0", null, null, null, "", "0", "0", "1", null, null, "(Crit); Stunned: 1", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", "1 round", "&lt;p&gt;You cloud the target's mind and daze it with a mental jolt. The jolt deals mental damage equal to your spellcasting ability modifier; the target must attempt a basic Will save. If the target critically fails the save, it is also stunned 1.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(+2) &lt;/b&gt;The damage increases by 1d6.&lt;/p&gt;", "7", null, "1", "Daze (7th)", "1", "60 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, divine, occult", "CANTRIP ENCHANTMENT MENTAL NONLETHAL"),

    DAZE_5TH(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, null, "will", null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d6,d6", null, "0", "0", "1", "mental")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( "0", null, null, null, "", "0", "0", "1", null, null, "(Crit); Stunned: 1", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", "1 round", "&lt;p&gt;You cloud the target's mind and daze it with a mental jolt. The jolt deals mental damage equal to your spellcasting ability modifier; the target must attempt a basic Will save. If the target critically fails the save, it is also stunned 1.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(+2) &lt;/b&gt;The damage increases by 1d6.&lt;/p&gt;", "5", null, "1", "Daze (5th)", "1", "60 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, divine, occult", "CANTRIP ENCHANTMENT MENTAL NONLETHAL"),

    DAZE_3RD(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, null, "will", null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d6", null, "0", "0", "1", "mental")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( "0", null, null, null, "", "0", "0", "1", null, null, "(Crit); Stunned: 1", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", "1 round", "&lt;p&gt;You cloud the target's mind and daze it with a mental jolt. The jolt deals mental damage equal to your spellcasting ability modifier; the target must attempt a basic Will save. If the target critically fails the save, it is also stunned 1.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(+2) &lt;/b&gt;The damage increases by 1d6.&lt;/p&gt;", "3", null, "1", "Daze (3rd)", "1", "60 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, divine, occult", "CANTRIP ENCHANTMENT MENTAL NONLETHAL"),

    DAZE_1ST(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, null, "will", null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "", null, "0", "0", "1", "mental")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( "0", null, null, null, "", "0", "0", "1", null, null, "(Crit); Stunned: 1", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", "1 round", "&lt;p&gt;You cloud the target's mind and daze it with a mental jolt. The jolt deals mental damage equal to your spellcasting ability modifier; the target must attempt a basic Will save. If the target critically fails the save, it is also stunned 1.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(+2) &lt;/b&gt;The damage increases by 1d6.&lt;/p&gt;", "1", null, "1", "Daze (1st)", "1", "60 feet", "0", "CANTRIP", "C", "H", "1 creature", "arcane, divine, occult", "CANTRIP ENCHANTMENT MENTAL NONLETHAL"),

    DANCING_LIGHTS(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, "(Sustained) Dancing Lights", null, null, null, "self", "effect")), null, "0", "&#143; somatic, verbal", "sustained", "&lt;p&gt;You create up to four floating lights, no two of which are more than 10 feet apart. Each sheds light like a torch. When you Sustain the Spell, you can move any number of lights up to 60 feet. Each light must remain within 120 feet of you and within 10 feet of all others, or it winks out.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;/p&gt;", "1", null, "1", "Dancing Lights", "1", "120 feet", "0", "CANTRIP", "C", null, null, "arcane, occult, primal", "CANTRIP EVOCATION LIGHT"),

    CHILL_TOUCH(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", "fortitude", null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d4", "oddcl", "0", "0", "1", "negative")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( "0", null, null, null, "", "0", "1", "1", null, null, "(Crit, Living); Enfeebled: 1", null, null, null, null, "effect"), new Action( "0", null, null, null, "", "0", "1", "1", null, null, "(Undead); Flat-footed", null, null, null, null, "effect"), new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", "will", null, "cast"), new Action( "0", null, null, null, "", "0", "1", "1", null, null, "(Crit, Undead); Fleeing", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;Siphoning negative energy into yourself, your hand radiates a pale darkness. Your touch weakens the living and disorients undead, possibly even causing them to flee. The effect depends on whether the target is living or undead.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Living Creature: &lt;/b&gt;The spell deals negative damage equal to 1d4 plus your spellcasting modifier. The target attempts a basic Fortitude save, but is also enfeebled 1 for 1 round on a critical failure.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Undead Creature: &lt;/b&gt;The target is flat-footed for 1 round on a failed Fortitude save. On a critical failure, the target is also fleeing for 1 round unless it succeeds at a Will save.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(+1) &lt;/b&gt;The negative damage to living creatures increases by 1d4.&lt;/p&gt;", "1", null, "1", "Chill Touch", "1", "touch", "0", "CANTRIP", "C", "H", "1 living or undead creature", "arcane, divine, occult", "CANTRIP NECROMANCY NEGATIVE"),

    ALLEGRO(Arrays.asList(new Action( "0", null, null, null, "", "0", "1", "1", null, null, "Allegro; Quickened; Strike, Stride, or Step", null, null, null, null, "effect")), null, "0", "&#141; verbal", "1 round", "&lt;p&gt;You perform rapidly, speeding up your ally. The ally becomes quickened and can use the additional action to Strike, Stride, or Step.&lt;/p&gt;", "corerulesfocusspellsbard", "&lt;p&gt;&lt;/p&gt;", "7", null, "1", "Allegro", "1", "30 feet", "0", "CANTRIP", "C", "U", "1 ally", null, "UNCOMMON BARD CANTRIP COMPOSITION EMOTION ENCHANTMENT MENTAL"),

    ACID_SPLASH_9TH(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d6,d6,d6,d6", null, "0", "0", "1", "acid")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, Arrays.asList(new HealDamage("4", "", null, "0", "0", "1", "acid, splash")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, null, null, null, null, null, null, null, null, null, "(Crit); PERS: 5 acid", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;You splash a glob of acid that splatters creatures and objects alike. Make a spell attack. If you hit, you deal 1d6 acid damage plus 1 splash acid damage. On a critical success, the target also takes 1 persistent acid damage.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(3rd) &lt;/b&gt;The initial damage increases to 1d6 + your spellcasting ability modifier, and the persistent damage increases to 2.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The initial damage increases to 2d6 + your spellcasting ability modifier, the persistent damage increases to 3, and the splash damage increases to 2.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The initial damage increases to 3d6 + your spellcasting ability modifier, the persistent damage increases to 4, and the splash damage increases to 3.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(9th) &lt;/b&gt;The initial damage increases to 4d6 + your spellcasting ability modifier, the persistent damage increases to 5, and the splash damage increases to 4.&lt;/p&gt;", "9", null, "1", "Acid Splash (9th)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 creature or object", "arcane, primal", "ACID ATTACK CANTRIP EVOCATION"),

    ACID_SPLASH_7TH(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d6,d6,d6", null, "0", "0", "1", "acid")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, Arrays.asList(new HealDamage("3", "", null, "0", "0", "1", "acid, splash")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, null, null, null, null, null, null, null, null, null, "(Crit); PERS: 4 acid", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;You splash a glob of acid that splatters creatures and objects alike. Make a spell attack. If you hit, you deal 1d6 acid damage plus 1 splash acid damage. On a critical success, the target also takes 1 persistent acid damage.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(3rd) &lt;/b&gt;The initial damage increases to 1d6 + your spellcasting ability modifier, and the persistent damage increases to 2.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The initial damage increases to 2d6 + your spellcasting ability modifier, the persistent damage increases to 3, and the splash damage increases to 2.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The initial damage increases to 3d6 + your spellcasting ability modifier, the persistent damage increases to 4, and the splash damage increases to 3.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(9th) &lt;/b&gt;The initial damage increases to 4d6 + your spellcasting ability modifier, the persistent damage increases to 5, and the splash damage increases to 4.&lt;/p&gt;", "7", null, "1", "Acid Splash (7th)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 creature or object", "arcane, primal", "ACID ATTACK CANTRIP EVOCATION"),

    ACID_SPLASH_5TH(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d6,d6", null, "0", "0", "1", "acid")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, Arrays.asList(new HealDamage("2", "", null, "0", "0", "1", "acid, splash")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, null, null, null, null, null, null, null, null, null, "(Crit); PERS: 3 acid", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;You splash a glob of acid that splatters creatures and objects alike. Make a spell attack. If you hit, you deal 1d6 acid damage plus 1 splash acid damage. On a critical success, the target also takes 1 persistent acid damage.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(3rd) &lt;/b&gt;The initial damage increases to 1d6 + your spellcasting ability modifier, and the persistent damage increases to 2.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The initial damage increases to 2d6 + your spellcasting ability modifier, the persistent damage increases to 3, and the splash damage increases to 2.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The initial damage increases to 3d6 + your spellcasting ability modifier, the persistent damage increases to 4, and the splash damage increases to 3.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(9th) &lt;/b&gt;The initial damage increases to 4d6 + your spellcasting ability modifier, the persistent damage increases to 5, and the splash damage increases to 4.&lt;/p&gt;", "5", null, "1", "Acid Splash (5th)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 creature or object", "arcane, primal", "ACID ATTACK CANTRIP EVOCATION"),

    ACID_SPLASH_3RD(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d6", null, "0", "0", "1", "acid")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, Arrays.asList(new HealDamage("1", "", null, "0", "0", "1", "acid, splash")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, null, null, null, null, null, null, null, null, null, "(Crit); PERS: 2 acid", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;You splash a glob of acid that splatters creatures and objects alike. Make a spell attack. If you hit, you deal 1d6 acid damage plus 1 splash acid damage. On a critical success, the target also takes 1 persistent acid damage.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(3rd) &lt;/b&gt;The initial damage increases to 1d6 + your spellcasting ability modifier, and the persistent damage increases to 2.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The initial damage increases to 2d6 + your spellcasting ability modifier, the persistent damage increases to 3, and the splash damage increases to 2.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The initial damage increases to 3d6 + your spellcasting ability modifier, the persistent damage increases to 4, and the splash damage increases to 3.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(9th) &lt;/b&gt;The initial damage increases to 4d6 + your spellcasting ability modifier, the persistent damage increases to 5, and the splash damage increases to 4.&lt;/p&gt;", "3", null, "1", "Acid Splash (3rd)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 creature or object", "arcane, primal", "ACID ATTACK CANTRIP EVOCATION"),

    ACID_SPLASH_1ST(Arrays.asList(new Action( null, null, null, null, null, null, null, null, null, null, null, null, "0", null, null, "cast"), new Action( null, Arrays.asList(new HealDamage("0", "d6", null, "0", "0", "1", "acid")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, Arrays.asList(new HealDamage("1", "", null, "0", "0", "1", "acid, splash")), null, "0", null, null, null, null, null, null, null, null, null, null, null, "damage"), new Action( null, null, null, null, null, null, null, null, null, null, "(Crit); PERS: 1 acid", null, null, null, null, "effect")), null, "0", "&#143; somatic, verbal", null, "&lt;p&gt;You splash a glob of acid that splatters creatures and objects alike. Make a spell attack. If you hit, you deal 1d6 acid damage plus 1 splash acid damage. On a critical success, the target also takes 1 persistent acid damage.&lt;/p&gt;", "corerules", "&lt;p&gt;&lt;b&gt;(3rd) &lt;/b&gt;The initial damage increases to 1d6 + your spellcasting ability modifier, and the persistent damage increases to 2.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(5th) &lt;/b&gt;The initial damage increases to 2d6 + your spellcasting ability modifier, the persistent damage increases to 3, and the splash damage increases to 2.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(7th) &lt;/b&gt;The initial damage increases to 3d6 + your spellcasting ability modifier, the persistent damage increases to 4, and the splash damage increases to 3.&lt;/p&gt;&lt;p&gt;&lt;b&gt;(9th) &lt;/b&gt;The initial damage increases to 4d6 + your spellcasting ability modifier, the persistent damage increases to 5, and the splash damage increases to 4.&lt;/p&gt;", "1", null, "1", "Acid Splash (1st)", "1", "30 feet", "0", "CANTRIP", "C", "H", "1 creature or object", "arcane, primal", "ACID ATTACK CANTRIP EVOCATION"),

    SPELL_NOT_FOUND();


    private List<Action> actions;

    private String area;

    private String cast;

    private String casting;

    private String duration;

    private String effects;

    private String filterCategory;

    private String heightened;

    private String level;

    private List<String> linkedSpells;

    private String locked;

    private String name;

    private String prepared;

    private String range;

    private String spCost;

    private String spellType;

    private String spellTypeLabel;

    private String superScripts;

    private String targets;

    private String traditions;

    private String traits;

    private CantripEnum(){
        this.name = "SPELL NOT FOUND";
    }
}
